version: '3.5'
##
# 
##
services:

  frontend:
    build: ./SearchEngineFrontend
    ports:
      - 80:80
    networks:
      app_net:
        ipv4_address: 172.18.18.2

  backend:
    build: ./SearchEngineBackend
    ports:
      - 5000:5000
    networks:
      app_net:
        ipv4_address: 172.18.18.3

  documentstore:
#    image: solr
    build: ./SearchEngineDatabase
    ports:
      - 8983:8983
    networks:
      app_net:
        ipv4_address: 172.18.18.4


networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.18.18.0/24